import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TrackingProvider } from "../../Context/Tracking";
import { NavBar,Footer } from "../../Components";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TrackingProvider>
        <NavBar/>
        {children}
        </TrackingProvider>
        <Footer/>
      </body>
    </html>
  );
}


// export default function App({Component,pageProps}) {
//   return <>
//   <TrackingProvider>
//   <Component {...pageProps} />
//   </TrackingProvider>
//   </>
// }